version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      # for production envs use vaults
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:./mongodatabase/src/main/resources

volumes:
  mongodb_data_container: